### PR TITLE
only stop service if it runs

### PR DESCRIPTION
**Pull request by GliderGeek**

### CODE REVIEW

**Comment by Evidlo** [comment]
Did this actually stop your installation?  I tested it on my machine and it continued on.

```
[evan@blackbox remarkable_news] make install_nyt
ssh-add
ssh root@10.11.99.1 systemctl stop renews
scp renews.arm root@10.11.99.1:
# substitute timezone/cooldown arguments
sed -e "s|TZ|America/Chicago|" -e "s|COOLDOWN|3600|" services/nyt.service > renews.service
# copy service to remarkable and enable
scp renews.service root@10.11.99.1:/etc/systemd/system/renews.service
ssh root@10.11.99.1 <<- ENDSSH
systemctl daemon-reload
systemctl enable renews
systemctl restart renews
ENDSSH
Enter passphrase for /home/evan/.ssh/id_rsa: 
Identity added: /home/evan/.ssh/id_rsa (/home/evan/.ssh/id_rsa)
Failed to stop renews.service: Unit renews.service not loaded.
renews.arm                                                    100%   11MB   5.9MB/s   00:01    
renews.service                                                100%  340   382.5KB/s   00:00    
Pseudo-terminal will not be allocated because stdin is not a terminal.
find: unrecognized: -printf
BusyBox v1.30.1 (2020-03-20 13:14:23 UTC) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
```

**Comment by GliderGeek** [comment]
Yes it did. In your test, did you remove the service first?

**Comment by Evidlo** [comment]
> Yes it did. In your test, did you remove the service first?

I did.

```
[evan@blackbox remarkable_news] ssh root@10.11.99.1
ｒｅＭａｒｋａｂｌｅ
╺━┓┏━╸┏━┓┏━┓   ┏━╸┏━┓┏━┓╻ ╻╻╺┳╸┏━┓┏━┓
┏━┛┣╸ ┣┳┛┃ ┃   ┃╺┓┣┳┛┣━┫┃┏┛┃ ┃ ┣━┫┗━┓
┗━╸┗━╸╹┗╸┗━┛   ┗━┛╹┗╸╹ ╹┗┛ ╹ ╹ ╹ ╹┗━┛

[root@remarkable ~] rm /etc/systemd/system/renews.service

[root@remarkable ~] systemctl stop renews
Warning: The unit file, source configuration file or drop-ins of renews.service changed on disk. Run 'systemctl daemon-reload' to reload units.

[root@remarkable ~] systemctl daemon-reload

[root@remarkable ~] logout
Connection to 10.11.99.1 closed.

[evan@blackbox remarkable_news] make install_nyt
Enter passphrase for /home/evan/.ssh/id_rsa: 
Identity added: /home/evan/.ssh/id_rsa (/home/evan/.ssh/id_rsa)
Failed to stop renews.service: Unit renews.service not loaded.
renews.arm                                                    100%   11MB   5.9MB/s   00:01    
renews.service                                                100%  340   372.3KB/s   00:00    
Pseudo-terminal will not be allocated because stdin is not a terminal.

[evan@blackbox remarkable_news] ssh root@10.11.99.1
ｒｅＭａｒｋａｂｌｅ
╺━┓┏━╸┏━┓┏━┓   ┏━╸┏━┓┏━┓╻ ╻╻╺┳╸┏━┓┏━┓
┏━┛┣╸ ┣┳┛┃ ┃   ┃╺┓┣┳┛┣━┫┃┏┛┃ ┃ ┣━┫┗━┓
┗━╸┗━╸╹┗╸┗━┛   ┗━┛╹┗╸╹ ╹┗┛ ╹ ╹ ╹ ╹┗━┛

[root@remarkable ~] systemctl status renews
● renews.service - New York Times
   Loaded: loaded (/etc/systemd/system/renews.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-05-01 20:53:19 UTC; 15s ago
 Main PID: 378 (renews.arm)
   CGroup: /system.slice/renews.service
           └─378 /home/root/renews.arm -output /usr/share/remarkable/suspended.png -verbose -ti>

May 01 20:53:19 remarkable systemd[1]: Started New York Times.

```

**Comment by GliderGeek** [comment]
i think i might have reacted to quickly on the question "Did this actually stop your installation?". i am not so sure anymore. will try again

**Comment by Evidlo** [comment]
So what's the news?

**Comment by Evidlo** [comment]
If there's still a problem, let me know.

**Comment by acrogenesis** [comment]
This was a problem for me too

**Pull request closed without merging**
