### PR TITLE
New York Times high quality

### PR DESCRIPTION
**Pull request by acrogenesis**
New york times high-quality image.
Solves #6

### CODE REVIEW

**Comment by acrogenesis** [comment]
I added to the readme
- New York Times (high quality provided by [https://github.com/acrogenesis/nyt-today](acrogenesis/nyt-today)) - `make install_nyt_hq`

**Comment by Evidlo** [comment]
I don't think the strftime or timezone options are needed.

**Comment by acrogenesis** [comment]
You are right, I've uploaded the change

**Comment by acrogenesis** [comment]
As a reference, this is how it looks:
IMG_3659

**Comment by Evidlo** [comment]
Thanks for the contribution.

**Pull request merged**
