### PR TITLE
Add ability to set title and subtitle

### PR DESCRIPTION
**Pull request by hashworks**
After I wrote this I noticed that there is already a very similar PR (#28). But I think I can trump that one, since this PR implements xpath support.

PXL_20231217_173731403 MP

### CODE REVIEW

**Comment by hashworks** [comment]
Closes #28.

**Comment by hashworks** [comment]
Closes #1.

**Comment by hashworks** [comment]
Labels that are too long are now split into two lines:
PXL_20231219_133312120

**Comment by Evidlo** [comment]
This is looking really good, and the pictures look nice!

Could I make a request to include a default font by [embedding Noto-Sans into the binary itself](https://stackoverflow.com/questions/13904441/whats-the-best-way-to-bundle-static-resources-in-a-go-program).  Not all systems will have NotoSans installed, and I'd like this to be as portable as possible.  NotoSans-Boldr.ttf seems to be only around 500KB.

**Comment by Evidlo** [comment]
Thanks, this has been a long sought-after feature

**Comment by hashworks** [comment]
This is a standard reMarkable Feature, just go to Settings -> Security -> Personal information ("Contact details to identify your reMarkable in sleep mode").

**Pull request merged**
